# Generated by Django 5.2.14 on 2026-06-07 04:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_version',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
