# Generated by Django 5.2.14 on 2026-05-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='flashcards/images/')),
                ('question_voice', models.FileField(blank=True, null=True, upload_to='flashcards/audio/')),
                ('answer_text', models.TextField()),
                ('is_premium_only', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order in the sequence')),
            ],
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mcqs/options/')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mcqs/images/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='mcqs/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_date', models.DateTimeField(auto_now_add=True)),
                ('interval_days', models.FloatField(default=0.0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.flashcard')),
            ],
        ),
    ]
