# Generated by Django 5.2.14 on 2026-05-10 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcqoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.mcqquestion'),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='subcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='learning.subcourse'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='subcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning.subcourse'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardprogress',
            unique_together={('user', 'flashcard')},
        ),
    ]
