# Generated by Django
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashcardProgress',
        ),
    ]
