# Generated by Django 5.2.14 on 2026-06-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_course_subcourse_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Priority for ordering. Lower numbers appear first.')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='subcourse',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority for ordering. Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='subcourse',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority for ordering. Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='learning.domain'),
        ),
    ]
