# Generated by Django 5.2.14 on 2026-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_domain_alter_course_options_alter_subcourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
