# Generated by Django 5.2.14 on 2026-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_course_price_subcourse_is_free_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcourse',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
