# Generated by Django 5.2.14 on 2026-06-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_course_icon_subcourse_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='is_premium_only',
        ),
    ]
