# Generated by Django 5.2.14 on 2026-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_flashcard_is_premium_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
