# Generated by Django 5.2.14 on 2026-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/images/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='answer_voice',
            field=models.FileField(blank=True, null=True, upload_to='flashcards/audio/'),
        ),
    ]
