# Generated by Django 5.2.14 on 2026-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_alter_flashcard_options_alter_mcqoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=255)),
                ('tree_month', models.CharField(max_length=100)),
                ('tree_file', models.FileField(upload_to='learning_trees/')),
            ],
        ),
    ]
